name: Run WP Automation Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444

    steps:
    # Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    # Install dependencies
    - name: Install dependencies
      run: |
        pip install selenium
        pip install python-dotenv

    # Install Chrome browser and ChromeDriver
    - name: Install Chrome and ChromeDriver
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        sudo apt-get install -y chromium-chromedriver

    # Set up environment variables
    - name: Set up environment variables
      run: |
        echo "WP_USERNAME=${{ secrets.WP_USERNAME }}" >> .env
        echo "WP_PASSWORD=${{ secrets.WP_PASSWORD }}" >> .env
        echo "CHROMEDRIVER_PATH=/usr/bin/chromedriver" >> .env

    # Run the test suite
    - name: Run Selenium tests
      run: |
        python test_suite.py
